### ISSUE TITLE
Additional attributes fail to load sometimes

### ISSUE THREAD

**Issue by tomillie** [tomillie/HockeyArenaRevampedPublic#67]
A tester reported an infinite loading of additional attributes in Line-up or Training.
It works fine for his U23 teams.

![Image](https://github.com/tomillie/HockeyArenaRevampedPublic/assets/2916757/8e906c67-8227-42f5-9315-fd059bf5c468)

**Comment by tomillie** [comment]
Stack trace:

> DataHelper.js:226 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'match')
    at Object.getPotentialGroupValue (DataHelper.js:226:99)
    at Object.isStatAboveTreshold (DataHelper.js:401:39)
    at Object.renderStat (DataHelper.js:423:48)
    at index.js:602:102
    at Array.forEach (<anonymous>)
    at index.js:587:28
    at Array.forEach (<anonymous>)
    at addColumnStat (index.js:585:17)
    at async Promise.all (/fi/index 1)
    at async init (index.js:654:9)

The error is probably caused by players older than 40, for which the potential group is not calculated and therefore it's missing in the storage (is undefined).
